
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: changeme.
      MYSQL_DATABASE: pvers
      MYSQL_USER: changeme
      MYSQL_PASSWORD: changeme.
      UPLOAD_LIMIT: 10000000000
    ports:
      - "9997:3306" 
    networks:
      - mydb
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ~/pvers-4x-mysql-data:/var/lib/mysql
  web:
    build: .
    restart: always
    container_name: pvers_web_app
    ports:
      - "8998:80"
    volumes:
      - ./:/var/www/html/
    networks:
      - mydb
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: changeme
      DB_PASSWORD: changeme.
      DB_NAME: pvers
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pvers_admin
    ports:
      - 8899:80
    environment:
      MYSQL_USER: changeme
      MYSQL_PASSWORD: changeme.
      MYSQL_ROOT_PASSWORD: changeme.
      UPLOAD_LIMIT: 10000000000
    networks:
      - mydb
volumes:
  db_data:

networks:
  mydb:
    driver: bridge